language: python

dist: bionic
sudo: false

env:
  global:
    # Doctr deploy key for bashtage/sphinx-material
    - secure: "eUjRfBZeS1KmH1HgBHDjRcgaJ7ktVRyUVH4YlxdZ2zADYvWqvB6gJ1DnOx0hDHv3IlEMt2BmjwL0y0HhjH/SG4t6bIBFnm1WH5ennpcCmDyyo3PFy3EeCPN59bHFLTj0L79FVMj+b39rDBsYoN2KpX6PsV6MLW8piRf6nsrzuWeFLawBQPRQvFpfbTDnhAUpChbyO8ExdKmG59GoyfSvAIzI86CO14ZRCygx3RVYPhudbHbvborL1ZSO74ZGgOtrHXrO6f/kP0giZFdXeaxMnb+vlSQGkNyPuX5EjJcHYe7Oj9rF8y6wV0UhGgdc0AMn5JDCJo//X/XZdJMeZ2qscFkx/Qzx38XC2LeG68w1qHPi54qUOL4Ud3jXSf2PeXM2aKXvhrVdThmpdLv2s3FTsviqpl6QrgWQMhYDPCZa7pmiId54So0UfLPTCuNenCZa/U+FxvL6cZGaCAg72sDOw0qYBpjSQaKcBsn0+uzmqOJgrRG2/H63CJQCFXbK4cMXBPtOGoNCYgv1E44wDHZ/BzflObp9XejooQxvrMntW5Xq0K9a5YXdLlgEv5RGvvAuhMHExaR6qaz5q+8wlxoZay8BFRpTYsimRbA9jkrna/WcAD2ZosVOeDSM9Cb1fz3uP4G5z2D5j+XgONjst38v6ts2fL3Nu1CbpHRVFkHeGJg="

git:
  depth: 1000

matrix:
  fast_finish: true
  include:
  - python: 3.7

before_install:
  - pip install pip --upgrade

install:
  - pip install -e .

script:
  - cd docs
  - pip install -r requirements.txt
  - make html

after_success:
  - cd ..
  - set -e
  - pip install doctr
  - doctr deploy --build-tags --built-docs docs/_build/html/ devel
  - |
    if [[ -z ${TRAVIS_TAG} ]]; then
      echo "Not a tagged build."
    else
      doctr deploy --build-tags --built-docs docs/_build/html/ .
    fi
